<?php
$staff = $block->getpart();
?>
<form>
    <table width="400px">
        <tr>
            <td>Nhap id de tim kiem</td>
            <td>
                <input type="text" name="member" id="memberpart" style="width=100px;">
            </td>
        </tr>

        <tr>
            <td>Result</td>
            <td><input type="text" name="nick_name" id="nick_name"></td>
        </tr>
        <tr>
            <td><input type="submit" value="Search" ></td>
        </tr>
    </table>

</form>


<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal'
    ], function ($, modal) {

        $('#memberpart').change(function () {
            var url = '<?php  echo $block->getUrl('staff/index/infor');?>';
            var id = $('#memberpart').val();

            var param = {
                id: id
            };

            $.ajax({
                showLoader: true,
                url: url,
                data: param,
                type: "POST",
                dataType: 'json'
            }).done(function (data) {

                $('#nick_name').attr('value', data.nick_name);


            })
        });


    })

</script>