<!---->
<!---->
<!--<form action="" method="post">-->
<!--    <table width="400px">-->
<!--        <tr>-->
<!--            <td>Bride email :</td>-->
<!--            <td><input type="text" id="bride"></td>-->
<!--        </tr>-->
<!---->
<!--        <tr>-->
<!--            <td>Groom  email :</td>-->
<!--            <td><input type="text"></td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <td><input type="submit" id="bride" name="send"></td>-->
<!--        </tr>-->
<!--    </table>-->
<!--</form>-->
<!---->
<!---->
<!--<form method="post">-->
<!--    <h1> Wedding title </h1>-->
<!--    <table width="400">-->
<!--            <td>Bride Names:<input type="text" id="bride_firstname" ></td>-->
<!--            <td><input type="checkbox">Send Email</td>-->
<!---->
<!--        <td>Bride Groom:<input type="text" id="groom_fristname"></td>-->
<!--        <td><input type="checkbox">Send Email</td>-->
<!---->
<!--        <tr>-->
<!--            <td>Amount:</td>-->
<!--            <td><input type="text"></td>-->
<!--            <td><input type="submit" value="add to cart"></td>-->
<!--        </tr>-->
<!--    </table>-->
<!--</form>-->
<!---->
<!---->
<!--<script>-->
<!--    require([-->
<!--        'jquery',-->
<!--        'Magento_Ui/js/modal/modal'-->
<!--    ], function ($, modal) {-->
<!---->
<!--        $('#bride').change(function () {-->
<!--            var url = '--><?php // echo $block->getUrl('wedding/index/handle');?>//';
//            var id = $('#bride').val();
//
//            var param = {
//                id: id
//            };
//
//            $.ajax({
//                showLoader: true,
//                url: url,
//                data: param,
//                type: "POST",
//                dataType: 'json'
//            }).done(function (data) {
//
//                $('#bride_firstname').attr('value', data.bride_firstname);
//                $('#groom_fristname').attr('value',data.groom_firstname);
//
//
//            })
//        });
//
//
//    })
//
//</script>