<?php
namespace  Magenest\Staff\Block\Adminhtml\Magenest;

use Magento\Backend\Block\Widget\Grid as WidgetGrid;

class Grid extends \Magento\Backend\Block\Widget\Grid\Extended {

    protected $_magennestCollection;



    public function __construct(\Magento\Backend\Block\Template\Context $context,
                                \Magento\Backend\Helper\Data $backendHelper,
                                \Magenest\Staff\Model\ResourceModel\Vendor\Collection $magennestCollection,
                                array $data = []
    ) {
        $this->_magennestCollection = $magennestCollection;
        parent::__construct($context, $backendHelper, $data);
        $this->setEmptyText(__('No Subscriptions Found'));
    }




    public function _prepareMassaction()
    {
        $this->setMassactionIdField('id');
        $this->getMassactionBlock()->setFormFieldName('Magenest');
        $this->getMassactionBlock()->addItem(
            'delete',
            [
                'label' => __('Delete'),
                'url' => $this->getUrl('staff/*/delete'),
                'confirm' => __('Are you sure ?'),
            ]
        );
        $this->getMassactionBlock()->addItem(
            'change status',
            [
                'label' => __('Change Status'),
                'url' => $this->getUrl('staff/*/changestatus'),
            ]
        );
        return $this;
    }


    public function getRowUrl($row)
    {
        return $this->getUrl('stafff/*/changestatus',['id'=>$row->getId()]);
    }



    /**
     * Initialize the subscription collection
     *
     * @return WidgetGrid
     */
    protected function _prepareCollection() {
        $this->setCollection($this->_magennestCollection);
        return parent::_prepareCollection(); // TODO: Change the autogenerated stub
    }
    /**
     * Prepare grid columns
     *
     * @return $this
     */
    protected function _prepareColumns() {
        $this->addColumn(
            'id',
            [
                'header' => __('ID'),
                'index' => 'id',
                'hidden'=>'true',
            ]
        );
        $this->addColumn(
            'name',
            [
                'header' => __('nick_name'),
                'index' => 'nick_name',
            ]
        );

        $this->addColumn(
            'type',
            [
                'header' => __('type'),
                'index' => 'type',
            ]
        );
        $this->addColumn(
            'status',
            [
                'header' => __('status'),
                'index' => 'status',
            ]
        );
      

        $this->addColumn(
            'update_at',
            [
                'header' => __('update_at'),
                'index' => 'update_at',
            ]
        );




    }

}

